### ISSUE TITLE
访问 '/' 不能重定向到 '/top'

### ISSUE THREAD

**Issue by Raincal** [dvajs/dva-hackernews#1]
你的在线demo可以重定向，我在本地就不行
我用dva-cli新建的项目用Redirect是没问题的

**Comment by sorrycc** [comment]
看下报什么错?

**Comment by Raincal** [comment]
![qq20160818-1](https://cloud.githubusercontent.com/assets/6279478/17773433/00a564ae-6581-11e6-98a0-2de7865c840d.png)
![qq20160818-0](https://cloud.githubusercontent.com/assets/6279478/17773435/03ba9024-6581-11e6-8d86-db4749c470ba.png)

**Comment by sorrycc** [comment]
你的代码不是最新的。

**Comment by sorrycc** [comment]
是 dva 的问题，一会修复。

**Comment by Raincal** [comment]
好的，辛苦了😊

**Comment by sorrycc** [comment]
修复了，dva 更新个小版本。
