### ISSUE TITLE
在线demo报错

### ISSUE THREAD

**Issue by ian4hu** [dvajs/dva-hackernews#4]
浏览器 Chrome 54.0.2840.71 (64-bit)
系统 macOS

复现步骤

1. 点击show，任选一条信息的 xx comments点击进入
2. 使用浏览器后退按钮返回到show列表页
3. 点击ask，进入ask列表页
4. 任选一条信息的 xx comments,点击报错

**Comment by sorrycc** [comment]
https://dvajs.github.io/dva-hackernews/#/item/12882816?_k=5cbtxj
重现了，直接访问 ask 的 comment 就会报错。

**Comment by ian4hu** [comment]
#6
