### ISSUE TITLE
设计上的顾虑

### ISSUE THREAD

**Issue by ian4hu** [dvajs/dva-hackernews#5]
粗略看了一下代码，发现是直接在model里面监听了路由，感觉这样的设计很少见，这样做是否存在弊端？或者说这个场景下这么做是合理的？

**Comment by sorrycc** [comment]
这样设计来自 elm 的 subscription，http://elm-lang.org/blog/farewell-to-frp

**Comment by ian4hu** [comment]
我的疑问点是在model里面去监听路由了，这么做是否不太好，或者说这里的一个监听路由是ok的？
